// Generated by tsup.config.ts from src/tools/*/index.ts. Do not edit.

import { tools as account } from "../tools/account/index.js";
import { tools as calendars } from "../tools/calendars/index.js";
import { tools as events } from "../tools/events/index.js";
import { tools as search } from "../tools/search/index.js";
import { tools as recurrence } from "../tools/recurrence/index.js";
import { tools as attendees } from "../tools/attendees/index.js";
import { tools as alarms } from "../tools/alarms/index.js";
import { tools as sync } from "../tools/sync/index.js";

export const TOOL_CATALOG = [
  ...account,
  ...calendars,
  ...events,
  ...search,
  ...recurrence,
  ...attendees,
  ...alarms,
  ...sync
];

export const TOOL_NAMES = TOOL_CATALOG.map((entry) => entry.name);
